# Generated by Django 2.0.5 on 2018-07-14 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=50)),
                ('MoviePoster', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('MovieRating', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('trailer', models.CharField(blank=True, max_length=100)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=200)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='SeatsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeatNumber', models.CharField(max_length=50)),
                ('SeatCost', models.IntegerField()),
                ('MovieDate', models.DateField(default=True)),
                ('MovieTime', models.CharField(max_length=50)),
                ('BookedDateTime', models.DateTimeField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheatreName', models.CharField(max_length=50)),
                ('TheatreAddress', models.CharField(max_length=200)),
                ('TheatreRating', models.IntegerField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Locations')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, upload_to='images/')),
                ('Wallet', models.IntegerField(blank=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seatsinfo',
            name='Theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Theatres'),
        ),
        migrations.AddField(
            model_name='seatsinfo',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
