# Generated by Django 2.0.5 on 2018-07-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
